admin_order:
    resource: "@AdminOrderBundle/Resources/config/routing.yml"
    prefix:   /admin/orders

admin_gallery:
    resource: "@AdminGalleryBundle/Resources/config/routing.yml"
    prefix:   /admin/gallery

admin_news:
    resource: "@AdminNewsBundle/Resources/config/routing.yml"
    prefix:   /admin/news

api_main:
    resource: "@APIMainBundle/Resources/config/routing.yml"
    prefix:   /api

admin_main:
    resource: "@AdminMainBundle/Resources/config/routing.yml"
    prefix:   /

#admin:
#    resource: "@AdminBundle/Resources/config/routing.yml"
#    prefix:   /admin

admin_page:
    resource: "@AdminPageBundle/Resources/config/routing.yml"
    prefix:   /admin/page

